### ISSUE TITLE
Sublinks are not rendered for 3rd hierarchy 

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-dev-website#3503]
**Description:**
Ideally More Samples should have a drop down to view more sublinks. The code is as follows 
```yaml
            - title: More Samples
              url: /learn/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda/#more-samples
              sublinks:
                - title: S3 Trigger
                  url: /learn/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda/#s3-trigger
                  active: s3-trigger
                - title: DynamoDB Trigger
                  url: /learn/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda/#dynamodb-trigger
                  active: dynamodb-trigger
```

However it does not show the dropdown.
![image](https://user-images.githubusercontent.com/23274047/151300973-27a4117e-8733-41c4-af63-d5c06dc44961.png)

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
